on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
    run-dnscontrol:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: gacts/install-dnscontrol@v1
      - run: dnscontrol preview
      # - run: dnscontrol push
      # - name: Actions Status Discord
      #   uses: sarisia/actions-status-discord@v1.14.5
      #   if: always()
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}