on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
    run-all:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Install DNS Control
        uses: gacts/install-dnscontrol@v1
      - name: Run DNSControl
        run: dnscontrol preview
        env:
          PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
          PORKBUN_SECRET_KEY: ${{ secrets.PORKBUN_SECRET_KEY }}

      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.14.5
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}