on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
    run-dnscontrol:
      runs-on: ubuntu-latest
      steps:
      - uses: gacts/install-dnscontrol@v1
      - run: dnscontrol preview
      - run: dnscontrol push

    notify-discord:
      runs-on: ubuntu-latest
      steps:
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.14.5
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}